/**
 * VitalPath AI — shared type definitions.
 * Mirrors the SwiftData / SQLAlchemy models on the native and backend sides.
 */

export type Language = "en" | "my" | "th" | "zh" | "ja" | "ko";

export type WellnessGoal =
  | "stress"
  | "sleep"
  | "nutrition"
  | "movement"
  | "mindfulness"
  | "hydration";

export interface WellnessProfile {
  id: string;
  displayName: string;
  preferredLanguage: Language;
  dietaryPreferences: string[]; // e.g. ["vegetarian", "low-sugar"]
  wellnessGoals: WellnessGoal[];
  comforts: string[]; // e.g. ["meditation", "walking"]
  avoid: string[]; // e.g. ["knee-stress"]
  streakDays: number;
  streakFreezeAvailable: boolean;
  lastCheckInISO?: string;
  createdAtISO: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  createdAtISO: string;
  // MCP metadata — which agent produced the reply
  agent?: "llama4" | "qwen35" | "qwen35vl" | "fallback";
  safetyFlags?: string[];
  // Suggested follow-ups generated by the coach
  suggestions?: string[];
}

export interface WellnessSession {
  id: string;
  kind: "chat" | "video" | "habit" | "breath";
  title: string;
  summary: string;
  moodScoreBefore?: number; // 1..5
  moodScoreAfter?: number; // 1..5
  tags: WellnessGoal[];
  durationSec: number;
  createdAtISO: string;
  synced: boolean;
}

export interface VideoAnalysis {
  id: string;
  mode: "meal" | "exercise";
  durationSec: number;
  thumbnailDataUrl?: string;
  nutritionEstimate?: string;
  formNotes?: string[];
  safetyFlag: boolean;
  cautions: string[];
  highlights: string[];
  score: number; // 0..100 wellness score
  createdAtISO: string;
}

export interface Habit {
  id: string;
  title: string;
  emoji: string;
  goal: WellnessGoal;
  targetPerWeek: number;
  completedThisWeek: number;
  history: string[]; // ISO dates
}

export interface CrisisEvent {
  id: string;
  triggerHash: string; // SHA-256 hash, never raw text
  language: Language;
  resolvedAtISO?: string;
  createdAtISO: string;
}

export interface CircuitBreakerState {
  status: "closed" | "open" | "half-open";
  failures: number;
  openedAtMs: number;
}
