/**
 * VitalPath AI — shared type definitions.
 * Mirrors the SwiftData / SQLAlchemy models on the native and backend sides.
 */

export type Language = "en" | "my" | "th" | "zh" | "ja" | "ko";

export type WellnessGoal =
  | "stress"
  | "sleep"
  | "nutrition"
  | "movement"
  | "mindfulness"
  | "hydration";

export interface WellnessProfile {
  id: string;
  displayName: string;
  preferredLanguage: Language;
  dietaryPreferences: string[]; // e.g. ["vegetarian", "low-sugar"]
  wellnessGoals: WellnessGoal[];
  comforts: string[]; // e.g. ["meditation", "walking"]
  avoid: string[]; // e.g. ["knee-stress"]
  streakDays: number;
  streakFreezeAvailable: boolean;
  lastCheckInISO?: string;
  createdAtISO: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  createdAtISO: string;
  // MCP metadata — which agent produced the reply
  agent?: "llama4" | "qwen35" | "qwen35vl" | "fallback";
  safetyFlags?: string[];
  // Suggested follow-ups generated by the coach
  suggestions?: string[];
}

export interface WellnessSession {
  id: string;
  kind: "chat" | "video" | "habit" | "breath";
  title: string;
  summary: string;
  moodScoreBefore?: number; // 1..5
  moodScoreAfter?: number; // 1..5
  tags: WellnessGoal[];
  durationSec: number;
  createdAtISO: string;
  synced: boolean;
}

export interface VideoAnalysis {
  id: string;
  mode: "meal" | "exercise";
  durationSec: number;
  thumbnailDataUrl?: string;
  nutritionEstimate?: string;
  formNotes?: string[];
  safetyFlag: boolean;
  cautions: string[];
  highlights: string[];
  score: number; // 0..100 wellness score
  createdAtISO: string;
}

export interface Habit {
  id: string;
  title: string;
  emoji: string;
  goal: WellnessGoal;
  targetPerWeek: number;
  completedThisWeek: number;
  history: string[]; // ISO dates
}

export interface CrisisEvent {
  id: string;
  triggerHash: string; // SHA-256 hash, never raw text
  language: Language;
  resolvedAtISO?: string;
  createdAtISO: string;
}

export interface CircuitBreakerState {
  status: "closed" | "open" | "half-open";
  failures: number;
  openedAtMs: number;
}

// ---------------------------------------------------------------------------
// Journaling
// ---------------------------------------------------------------------------

export interface JournalEntry {
  id: string;
  title: string;
  content: string;
  contentPreview: string;
  moodScore?: number; // 1..5
  tags: WellnessGoal[];
  createdAtISO: string;
  updatedAtISO: string;
}

// ---------------------------------------------------------------------------
// Knowledge-sharing community
// ---------------------------------------------------------------------------

export interface CommunityTopic {
  id: string;
  title: string;
  description: string;
  category: WellnessGoal;
  icon: string;
  memberCount: number;
  isOfficial: boolean;
  joined: boolean;
}

export interface CommunityPost {
  id: string;
  topicId: string;
  authorName: string;
  content: string;
  likeCount: number;
  replyCount: number;
  safetyFlags: string[];
  createdAtISO: string;
}

export interface CommunityReply {
  id: string;
  postId: string;
  authorName: string;
  content: string;
  createdAtISO: string;
}

// ---------------------------------------------------------------------------
// Breathwork + wellness planning
// ---------------------------------------------------------------------------

export type BreathPhase = "inhale" | "hold" | "exhale" | "hold2";

export interface BreathworkTechnique {
  id: string;
  name: string;
  summary: string;
  /** Phase durations in seconds, same length as `phases`. */
  pattern: number[];
  phases: BreathPhase[];
  rounds: number;
  benefits: string[];
  goal: WellnessGoal;
}

export type PlanTimeOfDay = "morning" | "midday" | "evening" | "night";

export type PlanKind =
  | "breath"
  | "movement"
  | "mindfulness"
  | "hydration"
  | "nutrition"
  | "reflection"
  | "sleep";

export interface PlanItem {
  id: string;
  time: PlanTimeOfDay;
  kind: PlanKind;
  title: string;
  summary: string;
  durationMin: number;
  goal: WellnessGoal;
  /** Present when this item launches a specific breathwork technique. */
  techniqueId?: string;
  completed: boolean;
}

export interface DailyPlan {
  id: string;
  /** YYYY-MM-DD */
  dateISO: string;
  items: PlanItem[];
}

export interface WeeklyPlan {
  id: string;
  /** YYYY-MM-DD of the Monday that begins this week. */
  weekStartISO: string;
  focus: WellnessGoal[];
  days: DailyPlan[];
}

// ---------------------------------------------------------------------------
// Sleep analytics
// ---------------------------------------------------------------------------

export interface SleepLog {
  id: string;
  dateISO: string;
  bedtimeISO?: string;
  waketimeISO?: string;
  durationMin: number;
  qualityScore: number;
  deepMin: number;
  remMin: number;
  lightMin: number;
  awakeMin: number;
  source: "manual" | "healthkit" | "wearable";
  notes: string;
  createdAtISO: string;
}

// ---------------------------------------------------------------------------
// Mood tracking
// ---------------------------------------------------------------------------

export interface MoodEntry {
  id: string;
  score: number; // 1..5
  energy: number; // 1..5
  tags: string[];
  note: string;
  createdAtISO: string;
}

export const MOOD_TAGS = [
  "grateful", "anxious", "calm", "tired", "energized",
  "focused", "stressed", "happy", "sad", "motivated",
  "overwhelmed", "peaceful", "irritable", "hopeful", "lonely",
] as const;

// ---------------------------------------------------------------------------
// AI weekly insights
// ---------------------------------------------------------------------------

export interface WeeklyInsight {
  id: string;
  weekISO: string;
  summary: string;
  highlights: string[];
  suggestions: string[];
  moodAvg?: number;
  sleepAvgMin?: number;
  streakDays: number;
  agent: string;
  createdAtISO: string;
}

// ---------------------------------------------------------------------------
// Social challenges
// ---------------------------------------------------------------------------

export interface Challenge {
  id: string;
  title: string;
  description: string;
  category: WellnessGoal;
  icon: string;
  targetDays: number;
  participantCount: number;
  isActive: boolean;
  joined: boolean;
  progressDays: number;
}
